# Form implementation generated from reading ui file 'interfejs.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(830, 657)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 831, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.verticalLayout.setContentsMargins(20, 0, 20, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnArtysci = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnArtysci.setObjectName("btnArtysci")
        self.verticalLayout.addWidget(self.btnArtysci)
        self.btnPlyty = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnPlyty.setObjectName("btnPlyty")
        self.verticalLayout.addWidget(self.btnPlyty)
        self.btnUtwory = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnUtwory.setObjectName("btnUtwory")
        self.verticalLayout.addWidget(self.btnUtwory)
        self.search = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.search.setObjectName("search")
        self.verticalLayout.addWidget(self.search)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(20, 170, 791, 431))
        self.tableView.setObjectName("tableView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 830, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnArtysci.setText(_translate("MainWindow", "Artyści"))
        self.btnPlyty.setText(_translate("MainWindow", "Płyty"))
        self.btnUtwory.setText(_translate("MainWindow", "Utwory"))
